apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"development"}}
  creationTimestamp: "2025-11-21T18:06:33Z"
  labels:
    kubernetes.io/metadata.name: development
  name: development
  resourceVersion: "336"
  uid: 27c64919-9cd6-48bd-8b4e-1640ef27b8d6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
